version: '3.8'

services:
  # PHP Application
  app:
    image: ${ECR_REPOSITORY_URI:-php:8.2-fpm}:latest
    container_name: laravel-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app-storage:/var/www/html/storage
      - app-public:/var/www/html/public
    networks:
      - laravel-network
    depends_on:
      - redis
    environment:
      # Configuración PostgreSQL RDS
      DB_CONNECTION: pgsql
      DB_HOST: ${RDS_HOST:-localhost}
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}

      # Configuración general
      REDIS_HOST: redis
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: "${APP_DEBUG:-false}"
      APP_KEY: ${APP_KEY}

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - app-public:/var/www/html/public
    networks:
      - laravel-network
    depends_on:
      - app

  # Redis for Cache and Queue
  redis:
    image: redis:alpine
    container_name: laravel-api-redis
    restart: unless-stopped
    networks:
      - laravel-network
    volumes:
      - redis-data:/data

# Volumes
volumes:
  redis-data:
    driver: local
  app-storage:
    driver: local
  app-public:
    driver: local

# Networks
networks:
  laravel-network:
    driver: bridge
