name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, zip, exif, pcntl, bcmath, gd

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  build:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Configurar variables
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"

            # Configurar ECR
            ECR_ACCOUNT="${{ secrets.AWS_ACCOUNT_ID }}"
            ECR_REGION="${{ secrets.AWS_REGION }}"
            ECR_URL="${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com"
            REPO_NAME="${{ secrets.AWS_ECR_REPOSITORY }}"
            REPO_URL="${ECR_URL}/${REPO_NAME}"

            # Login a ECR
            echo "Iniciando sesión en ECR..."
            aws ecr get-login-password --region ${ECR_REGION} | docker login --username AWS --password-stdin ${ECR_URL}

            # Pull de la imagen
            echo "Descargando imagen: ${REPO_URL}:latest"
            docker pull ${REPO_URL}:latest

            # Crear directorio para archivos de la aplicación
            mkdir -p ~/app-files/public
            mkdir -p ~/app-files/storage/framework/sessions
            mkdir -p ~/app-files/storage/framework/views
            mkdir -p ~/app-files/storage/framework/cache
            mkdir -p ~/app-files/storage/logs
            mkdir -p ~/app-files/bootstrap/cache

            # Crear un archivo test.php simple en la carpeta pública
            echo "<?php echo 'Hello from Laravel Test File!'; ?>" > ~/app-files/public/test.php
            chmod 755 ~/app-files/public/test.php

            # Reemplazar docker-compose.yml completamente con una versión que no sobrescriba los archivos de Laravel
            cat > ~/docker-compose.yml << EOF
            version: '3.8'

            services:
              # PHP Application
              app:
                image: ${REPO_URL}:latest
                container_name: laravel-api-app
                restart: unless-stopped
                volumes:
                  # Solo montamos storage para persistencia de datos, NO sobrescribimos public
                  - app-storage:/var/www/html/storage
                networks:
                  - laravel-network
                depends_on:
                  - db
                  - redis
                environment:
                  DB_HOST: db
                  DB_PORT: 3306
                  DB_DATABASE: ${{ secrets.RDS_DATABASE }}
                  DB_USERNAME: ${{ secrets.RDS_USERNAME }}
                  DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
                  REDIS_HOST: redis
                  APP_ENV: production
                  APP_DEBUG: "false"
                  APP_KEY: ${{ secrets.APP_KEY }}

              # Nginx Web Server
              nginx:
                image: nginx:alpine
                container_name: laravel-api-nginx
                restart: unless-stopped
                ports:
                  - "8080:80"
                volumes:
                  - ./nginx/conf.d:/etc/nginx/conf.d
                networks:
                  - laravel-network
                depends_on:
                  - app

              # MySQL Database
              db:
                image: mysql:8.0
                container_name: laravel-api-db
                restart: unless-stopped
                environment:
                  MYSQL_DATABASE: ${{ secrets.RDS_DATABASE }}
                  MYSQL_ROOT_PASSWORD: ${{ secrets.RDS_PASSWORD }}
                  MYSQL_PASSWORD: ${{ secrets.RDS_PASSWORD }}
                  MYSQL_USER: ${{ secrets.RDS_USERNAME }}
                volumes:
                  - mysql-data:/var/lib/mysql
                networks:
                  - laravel-network

              # Redis for Cache and Queue
              redis:
                image: redis:alpine
                container_name: laravel-api-redis
                restart: unless-stopped
                networks:
                  - laravel-network
                volumes:
                  - redis-data:/data

              # PHPMyAdmin for Database Management
              phpmyadmin:
                image: phpmyadmin/phpmyadmin
                container_name: laravel-api-phpmyadmin
                restart: unless-stopped
                ports:
                  - "8081:80"
                environment:
                  PMA_HOST: db
                  MYSQL_ROOT_PASSWORD: ${{ secrets.RDS_PASSWORD }}
                networks:
                  - laravel-network
                depends_on:
                  - db

            # Volumes
            volumes:
              mysql-data:
                driver: local
              redis-data:
                driver: local
              app-storage:
                driver: local

            # Networks
            networks:
              laravel-network:
                driver: bridge
            EOF

            # Crear una configuración Nginx sencilla que funcione
            mkdir -p ~/nginx/conf.d
            cat > ~/nginx/conf.d/default.conf << EOF
            server {
                listen 80;
                index index.php index.html;
                server_name _;
                error_log  /var/log/nginx/error.log;
                access_log /var/log/nginx/access.log;
                root /var/www/html/public;

                location / {
                    try_files \$uri \$uri/ /index.php?\$query_string;
                }

                location ~ \.php$ {
                    try_files \$uri =404;
                    fastcgi_split_path_info ^(.+\.php)(/.+)$;
                    fastcgi_pass app:9000;
                    fastcgi_index index.php;
                    include fastcgi_params;
                    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                    fastcgi_param PATH_INFO \$fastcgi_path_info;
                }
            }
            EOF

            # Iniciar contenedores con la nueva configuración
            docker-compose down
            docker-compose up -d

            # Esperar a que los contenedores estén listos
            echo "Esperando a que los contenedores estén listos..."
            sleep 15

            # CRUCIAL: Verificar si index.php existe, y si no, crearlo
            echo "Verificando archivos críticos de Laravel..."
            if ! docker exec laravel-api-app test -f /var/www/html/public/index.php; then
              echo "¡ATENCIÓN! Archivo index.php no encontrado. Creando uno básico..."
              docker exec laravel-api-app sh -c 'echo "<?php include_once __DIR__.'\''..'\''.'\''/'\''.'\''vendor/autoload.php'\''; $app = require_once __DIR__.'\''..'\''.'\''/'\''.'\''bootstrap/app.php'\''; $kernel = $app->make(Illuminate\\Contracts\\Http\\Kernel::class); $response = $kernel->handle($request = Illuminate\\Http\\Request::capture()); $response->send(); $kernel->terminate($request, $response); ?>" > /var/www/html/public/index.php'
              docker exec laravel-api-app chmod 755 /var/www/html/public/index.php
            fi

            # Verificar que los archivos críticos existen
            echo "Contenido del directorio public:"
            docker exec laravel-api-app ls -la /var/www/html/public/

            # Corregir permisos de archivos críticos
            echo "Configurando permisos correctos..."
            docker exec laravel-api-app sh -c "chmod -R 755 /var/www/html/public"
            docker exec laravel-api-app sh -c "chown -R www-data:www-data /var/www/html/storage"
            docker exec laravel-api-app sh -c "chown -R www-data:www-data /var/www/html/bootstrap/cache"

            # Crear un archivo de prueba PHP para verificar que todo funciona
            echo "Creando archivo de prueba..."
            docker exec laravel-api-app sh -c 'echo "<?php echo \"Test from container - setup by GitHub Actions\"; ?>" > /var/www/html/public/test-actions.php'
            docker exec laravel-api-app chmod 755 /var/www/html/public/test-actions.php

            # Reiniciar Nginx para aplicar todos los cambios
            docker restart laravel-api-nginx

            # Verificar que los contenedores estén en ejecución
            echo "Verificando estado de los contenedores..."
            docker ps

            # Verificar si el contenedor laravel-api-app existe antes de ejecutar migraciones
            if docker ps -q --filter "name=laravel-api-app" | grep -q .; then
              echo "Ejecutando migraciones..."
              docker exec -w /var/www/html laravel-api-app php artisan migrate --force
            else
              echo "ERROR: El contenedor laravel-api-app no está en ejecución. Verificando logs..."
              docker-compose logs app
              echo "Mostrando contenedores en ejecución:"
              docker ps -a
            fi

            # Mensaje de éxito con instrucciones
            echo "Despliegue completado con éxito!"
            echo "Prueba la aplicación en: http://$(curl -s http://checkip.amazonaws.com):8080"
            echo "Prueba el archivo de test en: http://$(curl -s http://checkip.amazonaws.com):8080/test-actions.php"
